baseURL = "https://niccarp11.github.io/"
languageCode = "en-us"
title = "Nicolò Carpentieri"
theme = "hugo-theme-motherfuckingwebsite"
enableRobotsTXT = true
paginate = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  author = 'Nicolò Carpentieri'
  dateform = 'Jan 02, 2006'
  Logo = '/images/nicolo.png'